package com.chaperon.dao;

import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.List;

import com.chaperon.model.SpatialScreeningResult.GisRecommendation;
import com.chaperon.model.SpatialScreeningResult.SpatialFinding;

public interface SpatialScreeningDAO {

    /*
     * Returns the latest project-boundary map associated with
     * the clearance application.
     */
    Long findLatestProjectMapId(
            long clearanceApplicationId
    ) throws SQLException;

    /*
     * Verifies that the selected map belongs to the given
     * clearance application and contains valid GeoJSON.
     */
    boolean projectBoundaryExists(
            long clearanceApplicationId,
            long clearanceMapId
    ) throws SQLException;

    /*
     * Returns the area stored when the entrepreneur drew the
     * project boundary.
     */
    BigDecimal findProjectAreaHectares(
            long clearanceMapId
    ) throws SQLException;

    /*
     * Returns project state for state-specific GIS layer
     * applicability. NULL GIS-layer state means All India.
     */
    String findProjectState(
            long clearanceApplicationId
    ) throws SQLException;

    /*
     * Returns project district for district-specific GIS layer
     * applicability.
     */
    String findProjectDistrict(
            long clearanceApplicationId
    ) throws SQLException;

    /*
     * Counts active GIS layers applicable to the project
     * location.
     */
    int countApplicableActiveLayers(
            String projectState,
            String projectDistrict
    ) throws SQLException;

    /*
     * Finds active GIS features whose geometry intersects the
     * entrepreneur project boundary.
     */
    List<SpatialFinding> findIntersectingFeatures(
            long clearanceMapId,
            String projectState,
            String projectDistrict
    ) throws SQLException;

    /*
     * Finds active GIS features within the supplied distance
     * from the entrepreneur project boundary.
     *
     * Distance is supplied in kilometres.
     */
    List<SpatialFinding> findNearbyFeatures(
            long clearanceMapId,
            String projectState,
            String projectDistrict,
            BigDecimal maximumDistanceKilometres
    ) throws SQLException;

    /*
     * Finds active applicability rules for a GIS layer
     * category and spatial relationship.
     *
     * spatialRelation:
     * INTERSECTS or DISTANCE_WITHIN
     */
    List<GisRecommendation> findApplicableRules(
            String layerCategory,
            String spatialRelation,
            BigDecimal actualDistanceKilometres,
            BigDecimal projectAreaHectares,
            String pollutionCategory,
            String projectState
    ) throws SQLException;

    /*
     * Deletes old system-generated spatial findings before a
     * fresh analysis is saved.
     */
    int deletePreviousSpatialAnalysis(
            long clearanceApplicationId
    ) throws SQLException;

    /*
     * Deletes old recommendations generated by the GIS engine.
     * Officer-confirmed recommendations must not be deleted.
     */
    int deletePreviousSystemRecommendations(
            long clearanceApplicationId
    ) throws SQLException;

    /*
     * Saves one intersection or proximity finding.
     */
    long saveSpatialFinding(
            long clearanceApplicationId,
            long clearanceMapId,
            SpatialFinding finding
    ) throws SQLException;

    /*
     * Saves one GIS-generated clearance recommendation.
     */
    long saveRecommendation(
            long clearanceApplicationId,
            GisRecommendation recommendation
    ) throws SQLException;

    /*
     * Prevents duplicate recommendations for the same
     * clearance type or normal approval.
     */
    boolean recommendationExists(
            long clearanceApplicationId,
            Long clearanceTypeId,
            Long approvalId
    ) throws SQLException;

    /*
     * Loads saved spatial findings for entrepreneur/officer UI.
     */
    List<SpatialFinding> findSavedFindings(
            long clearanceApplicationId
    ) throws SQLException;

    /*
     * Loads saved GIS recommendations for entrepreneur/officer
     * UI.
     */
    List<GisRecommendation> findSavedRecommendations(
            long clearanceApplicationId
    ) throws SQLException;

    /*
     * Officer confirms or rejects a system recommendation.
     *
     * status:
     * OFFICER_CONFIRMED or OFFICER_REJECTED
     */
    boolean updateRecommendationDecision(
            long gisRecommendationId,
            String status,
            long officerUserId,
            String officerRemarks
    ) throws SQLException;

    /*
     * Officer verifies an individual spatial analysis finding.
     */
    boolean verifySpatialFinding(
            long spatialAnalysisId,
            long officerUserId,
            String verificationStatus,
            String verificationRemarks
    ) throws SQLException;
}